---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-sqs-worker-job-controller-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-sqs-worker-job-controller-role
  namespace: default
rules:
  - apiGroups:
      - batch
      - awssqsworkerjobcontroller.k8s.io
    resources:
      - jobs
      - awssqsworkerjobs
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-sqs-worker-job-controller-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-sqs-worker-job-controller-role
subjects:
  - kind: ServiceAccount
    name: aws-sqs-worker-job-controller-serviceaccount
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-sqs-worker-job-controller-clusterrole
rules:
  - apiGroups:
      - batch
      - awssqsworkerjobcontroller.k8s.io
    resources:
      - jobs
      - awssqsworkerjobs
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-sqs-worker-job-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-sqs-worker-job-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: aws-sqs-worker-job-controller-serviceaccount
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sqs-worker-job-controller-deployment
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: aws-sqs-worker-job-controller
  template:
    metadata:
      labels:
        app: aws-sqs-worker-job-controller
    spec:
      serviceAccountName: aws-sqs-worker-job-controller-serviceaccount
      containers:
        - name: aws-sqs-worker-job-controller-container
          image: ghcr.io/supercaracal/aws-sqs-worker-job-controller:latest
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: AWS_ENDPOINT_URL
              value: "http://localstack-service.default.svc.cluster.local:4566"
            - name: AWS_ACCESS_KEY_ID
              value: "AAAAAAAAAAAAAAAAAAAA"
            - name: AWS_SECRET_ACCESS_KEY
              value: "0000000000000000000000000000000000000000"
            - name: SELF_NAMESPACE
              value: "default"
            - name: TZ
              value: "Asia/Tokyo"
          resources:
            requests:
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
