---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller
rules:
  - apiGroups:
      - batch
      - awssqsworkerjob.k8s.io
      - ""
    resources:
      - events
      - jobs
      - awssqsworkerjobs
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
rules:
  - apiGroups:
      - batch
      - awssqsworkerjob.k8s.io
    resources:
      - jobs
      - awssqsworkerjobs
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: aws-sqs-worker-job-controller
  template:
    metadata:
      labels:
        app: aws-sqs-worker-job-controller
    spec:
      serviceAccountName: controller
      containers:
        - name: main
          image: ghcr.io/supercaracal/aws-sqs-worker-job-controller:latest
          env:
            - name: AWS_REGION
              value: "ap-northeast-1"
            - name: AWS_ENDPOINT_URL
              value: "http://localstack.default.svc.cluster.local:4566"
            - name: AWS_ACCESS_KEY_ID
              value: "AAAAAAAAAAAAAAAAAAAA"
            - name: AWS_SECRET_ACCESS_KEY
              value: "0000000000000000000000000000000000000000"
            - name: SELF_NAMESPACE
              value: "default"
            - name: TZ
              value: "Asia/Tokyo"
          resources:
            requests:
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
