apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workerjobs.awssqsworkerjobcontroller.k8s.io
spec:
  group: awssqsworkerjobcontroller.k8s.io
  version: v1
  names:
    kind: WorkerJob
    plural: workerjobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            queue:
              type: string
              pattern: '^[a-zA-Z0-9._-]{1,80}$'
