---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awssqsworkerjobs.awssqsworkerjobcontroller.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: awssqsworkerjobcontroller.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                queueUrl:
                  type: string
  scope: Namespaced
  names:
    kind: AwsSqsWorkerJob
    singular: awssqsworkerjob
    plural: awssqsworkerjobs
    shortNames:
      - aswj
