---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: localstack
spec:
  serviceName: localstack
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack
      app.kubernetes.io/part-of: supercaracal.example.com
      app.kubernetes.io/component: cloud-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack
        app.kubernetes.io/part-of: supercaracal.example.com
        app.kubernetes.io/component: cloud-service
    spec:
      containers:
        - name: main
          image: localstack/localstack:latest
          env:
            - name: SERVICES
              value: "sqs"
            - name: DEFAULT_REGION
              value: "ap-northeast-1"
            - name: DEBUG
              value: "1"
            - name: FORCE_NONINTERACTIVE
              value: "1"
            - name: TZ
              value: "Asia/Tokyo"
          ports:
            - containerPort: 4566
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["awslocal", "sqs", "list-queues"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/part-of: supercaracal.example.com
    app.kubernetes.io/component: cloud-service
  ports:
    - name: "edge-port"
      protocol: "TCP"
      port: 4566
      targetPort: 4566
