---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-awssqsworkerjob-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sleep-awssqsworkerjob-role
  namespace: default
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sleep-awssqsworkerjob-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sleep-awssqsworkerjob-role
subjects:
  - kind: ServiceAccount
    name: sleep-awssqsworkerjob-serviceaccount
    namespace: default

---
apiVersion: awssqsworkerjobcontroller.k8s.io/v1
kind: AWSSQSWorkerJob
metadata:
  name: sleep-awssqsworkerjob
  namespace: default
spec:
  queueURL: "http://localhost:4566/000000000000/sleep-queue"
  template:
    spec:
      serviceAccountName: sleep-awssqsworkerjob-serviceaccount
      containers:
        - name: sleeper
          image: alpine:latest
          command:
            - "/bin/sleep"
          args:
            - "180" # default
          env:
            - name: TZ
              value: "Asia/Tokyo"
          resources:
            requests:
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
