---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-awssqsworkerjob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sleep-awssqsworkerjob
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sleep-awssqsworkerjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sleep-awssqsworkerjob
subjects:
  - kind: ServiceAccount
    name: sleep-awssqsworkerjob

---
apiVersion: supercaracal.example.com/v1
kind: AWSSQSWorkerJob
metadata:
  name: sleep-awssqsworkerjob
spec:
  queueURL: "http://localstack.default.svc.cluster.local:4566/000000000000/sleep-queue.fifo"
  historyLimit: 3
  template:
    spec:
      serviceAccountName: sleep-awssqsworkerjob
      containers:
        - name: main
          image: alpine:latest
          command:
            - "/bin/sleep"
          args:
            - "180" # default
          env:
            - name: TZ
              value: "Asia/Tokyo"
          resources:
            requests:
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
