---
name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        go-ver: ["1.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Add $GOPATH/bin to $PATH
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Get dependencies
        run: |
          go get -u\
            golang.org/x/lint/golint\
            k8s.io/code-generator/...

      - name: Print Go env
        run: go env

      - name: Generate several codes
        run: make codegen

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Lint docker image
        run: make lint-image
        if: runner.os == 'Linux'

      - name: Build docker image
        run: make build-image
        if: runner.os == 'Linux'
